"""Xuất bảng mốc thời gian để dựng lại video không phụ đề.

Kịch bản trong app là nguồn duy nhất. Bản dựng mới phải khớp đúng các mốc này,
vì app dừng lại hỏi và hiện phụ đề theo giây cố định chứ không dò theo hình.
Lệch mốc thì câu hỏi bật ra giữa chừng một cảnh.
"""
import io
import re
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

OUT = "docs/beat-sheet.md"


def parse():
    src = io.open("lib/data/session_script.dart", encoding="utf-8").read()
    beats = []
    for m in re.finditer(
            r"Beat\(\s*number: (\d+),\s*id: '([^']+)',\s*"
            r"titleVi: '([^']+)',\s*titleEn: '([^']+)',\s*"
            r"start: _ms\(([\d.]+)\),\s*end: _ms\(([\d.]+)\)", src):
        beats.append({
            "number": int(m.group(1)),
            "id": m.group(2),
            "en": m.group(4),
            "start": float(m.group(5)),
            "end": float(m.group(6)),
        })
    return beats


def mmss(seconds):
    return f"{int(seconds) // 60}:{int(seconds) % 60:02d}"


def main():
    beats = parse()
    if not beats:
        raise SystemExit("khong doc duoc beat nao — kiem tra lai session_script.dart")

    rows = "\n".join(
        f"| {b['number']} | {mmss(b['start'])} | {mmss(b['end'])} | "
        f"{int(b['end'] - b['start'])}s | {b['en']} |"
        for b in beats)

    doc = f"""# Beat sheet — for re-rendering the countryside video

The application follows playback position on a fixed clock. It pauses to ask a
question, and shows each caption, at the second given below. It does not watch
the picture. **A new render must keep these boundaries**, or a question will
interrupt the middle of a shot.

Total length: **{mmss(beats[-1]['end'])}** exactly ({int(beats[-1]['end'])}.000 seconds).

## What to change

Remove everything painted into the picture:

- the English subtitles along the bottom
- the "Beat N · ..." production label in the top-left corner
- any watermark

Nothing else has to match the current video. The shots may be entirely
different; only the timings are fixed.

## What to deliver

| | |
|---|---|
| Length | {int(beats[-1]['end'])}.000 s, exactly |
| Aspect | 16:9 |
| Resolution | 1280x720 or higher — higher is welcome, it will be scaled down |
| Text in picture | none at all |
| Audio | not needed; ambient sound and the narration are mixed in separately |
| Format | anything FFmpeg reads |

## Beat boundaries

| Beat | Starts | Ends | Length | What this part is |
|---|---|---|---|---|
{rows}

## Two notes

Beat 5 is the breathing section and carries no captions in the application —
it is a minute of quiet, so the picture should be able to hold attention on its
own.

Four beats end with a question, and the application pauses 250 ms before the
boundary to ask it. A shot that ends on a clean, calm frame at those moments
will look better than one cut mid-movement: {', '.join(
        mmss(b['end']) for b in beats if b['id'] in
        ('safety', 'checkin', 'preparation', 'feedback'))}.

*Generated by `tools/video/export_beat_sheet.py` from
`lib/data/session_script.dart`. Re-run it rather than editing this file.*
"""
    io.open(OUT, "w", encoding="utf-8").write(doc)
    print("viet", OUT)
    for b in beats:
        print(f"  beat {b['number']:2d}  {mmss(b['start'])}–{mmss(b['end'])}  "
              f"{b['en']}")


main()
