"""Sinh báo cáo tương phản WCAG 2.2 từ chính màu app đang dùng.

Báo cáo viết tay thì đúng đúng một ngày. Cái này đọc bảng màu Flutter sinh ra
(`build/scheme.json`), đọc màu tâm trạng thẳng từ `lib/models/mood.dart`, rồi
in ra `docs/wcag-audit.md`. Muốn báo cáo mới thì chạy lại, không sửa tay.

Ngưỡng nằm trong `contrast.py`; phần ràng buộc để không ai lỡ tay hạ chuẩn nằm
trong `test/contrast_test.dart`.
"""
import io
import json
import os
import re
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from contrast import PAIRS, blend, luminance, ratio, threshold  # noqa: E402

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

OUT = "docs/wcag-audit.md"
BRIGHTEST_VIDEO = 0.531   # đo bằng caption_background.py

# Công cụ chạy bằng tiếng Việt, báo cáo thì gửi cho hội đồng quốc tế.
EN = {
    "Chữ thân bài trên nền trang": "Body text on the page",
    "Tiêu đề lớn trang mở đầu": "Launch-page heading",
    "Chữ phụ trên nền trang": "Secondary text on the page",
    "Chữ nhỏ trên nền trang": "Small text on the page",
    "Tiêu đề thẻ": "Card heading",
    "Chữ nhỏ trong thẻ": "Small text inside a card",
    "Nhãn nút chính": "Primary button label",
    "Nhãn thẻ chọn đang chọn": "Selected chip label",
    "Nhãn thẻ chọn chưa chọn": "Unselected chip label",
    "Nhãn ô bối cảnh đang chọn": "Selected setting, title",
    "Mô tả ô bối cảnh đang chọn": "Selected setting, description",
    "Chữ trong ô nhập": "Text in an input field",
    "Nhãn báo lỗi": "Error label",
    "Chữ trong thanh thông báo": "Text in a snack bar",
    "Biểu tượng nhấn mạnh": "Accent icon on the page",
    "Biểu tượng trong thẻ": "Accent icon inside a card",
    "Nút chính so với nền trang": "Primary button against the page",
    "Dấu tích ô bối cảnh đang chọn": "Selected-setting tick",
    "Viền ngoài": "Outline",
}


def mood_colours():
    """Đọc năm mức tâm trạng và hai sắc của mỗi mức từ mã nguồn."""
    src = io.open("lib/models/mood.dart", encoding="utf-8").read()
    out = []
    for m in re.finditer(
            r"(\w+)\(\s*score: (\d+),\s*label: '([^']+)',.*?"
            r"onLight: Color\(0x(\w{8})\),\s*onDark: Color\(0x(\w{8})\),",
            src, re.S):
        out.append({
            "id": m.group(1), "label": m.group(3),
            "light": "#" + m.group(4)[2:], "dark": "#" + m.group(5)[2:],
        })
    return out


def scrim_levels():
    src = io.open("lib/widgets/session_chrome.dart", encoding="utf-8").read()
    return {k: float(v) for k, v in
            re.findall(r"static const (\w+) = (0\.\d+);", src)}


def rows_for(scheme, moods, key):
    colors = dict(scheme)
    colors["_inputFill"] = blend(colors["surfaceContainerHighest"],
                                 colors["surface"], 0.5)
    rows = []
    for desc, fg, bg, size, bold, kind in PAIRS:
        if fg == "outlineVariant":
            continue   # chỉ dùng làm kẻ ô biểu đồ, xem phần "Được miễn"
        need, sc = threshold(size, bold, kind)
        rows.append((EN.get(desc, desc), sc, need,
                     ratio(colors[fg], colors[bg])))
    for mood in moods:
        c = mood[key]
        rows.append((f'"{mood["label"]}" bar against its track', "SC 1.4.11",
                     3.0, ratio(c, colors["surfaceContainerHighest"])))
        rows.append((f'"{mood["label"]}" dot on a card', "SC 1.4.11", 3.0,
                     ratio(c, colors["surfaceContainerLow"])))
    return rows


def table(rows):
    out = ["| Element | Criterion | Required | Measured | |",
           "|---|---|---|---|---|"]
    for desc, sc, need, got in rows:
        mark = "pass" if got >= need else "**FAIL**"
        out.append(f"| {desc} | {sc} | {need}:1 | {got:.2f}:1 | {mark} |")
    return "\n".join(out)


def _over_white(alpha):
    """Độ chói của nền trắng sau khi bị phủ một lớp đen [alpha]."""
    v = round((1 - alpha) * 255)
    return luminance("#%02x%02x%02x" % (v, v, v))


def main():
    scheme = json.load(io.open("build/scheme.json", encoding="utf-8"))
    moods = mood_colours()
    scrim = scrim_levels()
    light = rows_for(scheme["light"], moods, "light")
    dark = rows_for(scheme["dark"], moods, "dark")
    every = light + dark
    failed = [r for r in every if r[3] < r[2]]
    worst = min(every, key=lambda r: r[3] / r[2])

    plate = 1.05 / (_over_white(scrim["captionPlate"]) + 0.05)
    bar = 1.05 / (_over_white(scrim["bar"]) + 0.05)
    bare = 1.05 / (BRIGHTEST_VIDEO + 0.05)

    doc = f"""# Colour contrast audit — WCAG 2.2

Generated {date.today().isoformat()} by `tools/a11y/report.py`. Every number
below is measured from the colours the application actually renders, not from a
style guide. Re-run the tool after any colour change; do not edit this file.

## Result

**{len(every) - len(failed)} of {len(every)} pairs pass.** The narrowest margin
is *{worst[0]}* at {worst[3]:.2f}:1 against a {worst[2]}:1 requirement.

The same thresholds are enforced by `test/contrast_test.dart`, which runs with
the ordinary test suite. A colour change that drops below a threshold fails the
build rather than quietly shipping.

## Method

Contrast is computed per WCAG 2.2 from relative luminance, with sRGB values
linearised before weighting. Thresholds: SC 1.4.3 requires 4.5:1 for normal
text and 3:1 for large text (>=24px, or >=18.7px bold); SC 1.4.11 requires
3:1 for user-interface components and for graphical objects that carry meaning.

Pairs were chosen because they appear on screen, not because they exist in the
palette. Semi-transparent layers are blended first, so what is measured is what
the eye receives.

## Text over video

This is the case a palette-only audit misses. Captions are positioned against
the screen, not against the video frame, so on a short, wide window — a phone
browser held sideways, a tablet — they fall on the picture itself.

All 14,400 frames of both settings were scanned for the brightest band a line
of text could land on. The worst is a relative luminance of {BRIGHTEST_VIDEO},
which gives white text **{bare:.2f}:1** — well below the 4.5:1 required.

Three fixes followed:

| Layer | Treatment | Worst case now |
|---|---|---|
| Caption | Opaque backing plate at {scrim['captionPlate']:.0%} black | {plate:.2f}:1 |
| Top and bottom bars | Scrim held at {scrim['bar']:.0%} black across the text area before fading | {bar:.2f}:1 |
| Small labels | Changed from 70% white to full white | as above |

The plate is computed against pure white, so those figures are floors that hold
for any frame. Over the black letterbox on a phone the plate is invisible, so
nothing changed on the layout most people will see.

## Light theme

{table(light)}

## Dark theme

{table(dark)}

## Exempt, with reasons

| Item | Why it is not a failure |
|---|---|
| Chart gridlines | Decorative. The values are carried by the axis labels and by the position of each point, not by the lines. |
| Mood colours as the only cue | Not applicable: every mood is shown with an emoji, a written label and a count, so SC 1.4.1 is satisfied without relying on colour. |
| Disabled controls | Exempt under SC 1.4.3 and SC 1.4.11. |

## What changed to get here

Five mood colours were failing in the light theme, between 1.28:1 and 2.85:1.
They were Material 300-weight tints — comfortable on a dark background,
invisible on a light one. Each mood now carries two shades and picks the one
that suits the background.

Tuning them exposed a second problem the eye would have caught eventually: the
darkened amber for "Okay" landed 22 degrees of hue from the darkened orange for
"Not great", at almost identical lightness. Two adjacent levels on a five-point
scale looked like one colour. "Okay" was moved towards olive.

The bottom-sheet drag handle used a divider colour at 1.62:1. It tells the user
the sheet can be pulled, so it carries information and now uses a visible
outline colour.

## Other WCAG 2.2 criteria

Outside colour, the criteria new in 2.2 that apply here:

| Criterion | Status |
|---|---|
| 2.5.8 Target Size (Minimum), 24x24 | Pass. Controls are 52–56px. |
| 2.4.11 Focus Not Obscured (Minimum) | Needs a check on the question sheet, which slides over the screen. Not yet verified. |
| 3.3.7 Redundant Entry | Not applicable. Stress is asked before and after on purpose — that is a measurement, not a repeated question. |
| 3.2.6 Consistent Help | The stop control and "Skip this question" appear in the same place throughout. |

Keyboard navigation and screen-reader flow have not been audited. That is the
next accessibility task, and it is a larger one than colour.
"""
    io.open(OUT, "w", encoding="utf-8").write(doc)
    print("viet", OUT)
    print(f"{len(every) - len(failed)}/{len(every)} cap dat")
    print("hep nhat:", worst[0], f"{worst[3]:.2f}:1")


main()
